# Control table address
ADDR_PRO_TORQUE_ENABLE      = 64               # Control table address is different in Dynamixel model
ADDR_OPERATING_MODE=11

ADDR_PRO_GOAL_POSITION      = 116
ADDR_PRO_GOAL_CURRENT=102
ADDR_PRO_GOAL_VELOCITY=104
ADDR_PRO_GOAL_PWM=100

ADDR_PRO_PRESENT_POSITION   = 132
ADDR_PRO_PRESENT_CURRENT=126
ADDR_PRO_PRESENT_VELOCITY=128
ADDR_PRO_PRESENT_PWM=124

ADDR_PRO_HOMING_OFFSET=20