# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controlLoop import controlWrapper



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 602)
        self.controllerWrapper=controlWrapper()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 80, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.motorPortTB = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.motorPortTB.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.motorPortTB.setObjectName("motorPortTB")
        self.indicatorPortTB = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.indicatorPortTB.setGeometry(QtCore.QRect(20, 50, 121, 31))
        self.indicatorPortTB.setObjectName("indicatorPortTB")
        self.logTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.logTB.setEnabled(True)
        self.logTB.setGeometry(QtCore.QRect(10, 380, 861, 192))
        self.logTB.setObjectName("logTB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 161, 31))
        self.label_2.setObjectName("label_2")
        self.sensor2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.sensor2.setGeometry(QtCore.QRect(780, 90, 64, 23))
        self.sensor2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.sensor2.setProperty("value", 0.0)
        self.sensor2.setObjectName("sensor2")
        self.setPoint1TB = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.setPoint1TB.setGeometry(QtCore.QRect(650, 30, 104, 31))
        self.setPoint1TB.setObjectName("setPoint1TB")
        self.setPoint2TB = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.setPoint2TB.setGeometry(QtCore.QRect(650, 80, 104, 31))
        self.setPoint2TB.setObjectName("setPoint2TB")
        self.setSetpointButton = QtWidgets.QPushButton(self.centralwidget)
        self.setSetpointButton.setGeometry(QtCore.QRect(670, 130, 121, 31))
        self.setSetpointButton.setObjectName("setSetpointButton")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(320, 20, 71, 31))
        self.connectButton.setObjectName("connectButton")
        self.motor1CalButton = QtWidgets.QPushButton(self.centralwidget)
        self.motor1CalButton.setGeometry(QtCore.QRect(340, 280, 231, 41))
        self.motor1CalButton.setObjectName("motor1CalButton")
        self.motor2CalButton = QtWidgets.QPushButton(self.centralwidget)
        self.motor2CalButton.setGeometry(QtCore.QRect(340, 326, 231, 41))
        self.motor2CalButton.setObjectName("motor2CalButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 30, 121, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 90, 121, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 360, 41, 21))
        self.label_5.setObjectName("label_5")
        self.dataCollectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataCollectionButton.setGeometry(QtCore.QRect(20, 126, 151, 31))
        self.dataCollectionButton.setObjectName("dataCollectionButton")
        self.dataCollectionProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.dataCollectionProgressBar.setGeometry(QtCore.QRect(210, 130, 191, 23))
        self.dataCollectionProgressBar.setProperty("value", 0)
        self.dataCollectionProgressBar.setObjectName("dataCollectionProgressBar")
        self.dataCollectionGraphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.dataCollectionGraphicsView.setGeometry(QtCore.QRect(20, 160, 256, 192))
        self.dataCollectionGraphicsView.setObjectName("dataCollectionGraphicsView")
        self.setPointGraphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.setPointGraphicsView.setGeometry(QtCore.QRect(600, 170, 256, 192))
        self.setPointGraphicsView.setObjectName("setPointGraphicsView")
        self.sensor1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.sensor1.setGeometry(QtCore.QRect(780, 40, 64, 23))
        self.sensor1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.sensor1.setProperty("value", 0.0)
        self.sensor1.setObjectName("sensor1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.homeButtonEvent)
        self.connectButton.clicked.connect(self.connectButtonEvent)
        self.setSetpointButton.clicked.connect(self.setPointButtonEvent)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "COM Port of Dynamixel"))
        self.label_2.setText(_translate("MainWindow", "COM Port of Indicator"))
        self.setSetpointButton.setText(_translate("MainWindow", "Write SetPoint"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.motor1CalButton.setText(_translate("MainWindow", "Motor 1 Friction Calibration"))
        self.motor2CalButton.setText(_translate("MainWindow", "Motor 2 Friction Calibration"))
        self.label_3.setText(_translate("MainWindow", "Motor 1 SetPoint"))
        self.label_4.setText(_translate("MainWindow", "Motor 2 SetPoint"))
        self.label_5.setText(_translate("MainWindow", "Log"))
        self.dataCollectionButton.setText(_translate("MainWindow", "Start Data Collection"))

    def connectButtonEvent(self):
        self.controllerWrapper.motorPort=self.motorPortTB.toPlainText()
        self.controllerWrapper.sensorPort=self.indicatorPortTB.toPlainText()
        self.controllerWrapper.connect()
    
    def homeButtonEvent(self):
        self.controllerWrapper.homeMotors()
    def setPointButtonEvent(self):
        s1=float(self.setPoint1TB.toPlainText())
        s2=float(self.setPoint2TB.toPlainText())
        setpoints=[s1,s2]
        self.controllerWrapper.updateSetPoints(setpoints)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
